"""``workflow-orchestrator wiki init`` — scaffold a consolidated wiki repo.

SRS §4.5 describes a wiki repo whose page directories sit directly under
``llm-wiki/``. SRS §1.2 rules out migrating the existing personal vault into it,
so a fresh repo has to be created — this builds the skeleton and, optionally,
seeds ``schema.md`` and ``AGENTS.md`` from an existing vault so the ``wiki-*``
command vocabulary carries over.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from ..logging import get_logger
from .layout import AGENTS_FILE, PAGE_DIRS, WIKI_ROOT, layout_for

log = get_logger(__name__)

INDEX_TEMPLATE = """\
# Wiki Index

Generated by `workflow-orchestrator wiki init`. The Librarian keeps this file
current; every automated write appends here and to `log.md`.

## Super Summaries

_none yet_

## Concepts

_none yet_

## Summaries

_none yet_
"""

LOG_TEMPLATE = """\
# Wiki Log

Append-only record of wiki operations.
"""

SCHEMA_PLACEHOLDER = """\
# Wiki Schema

> This is a placeholder. `schema.md` is the authoritative operating manual for
> wiki procedures, content rules and file ownership — seed it from an existing
> vault with:
>
>     workflow-orchestrator wiki init <path> --seed-from /path/to/vault
"""

AGENTS_PLACEHOLDER = """\
# Codex Instructions — Wiki Repo

This repo contains an LLM Wiki at `llm-wiki/`. Before performing any wiki
operation, read `llm-wiki/schema.md` in full.

## Boundary rule (non-negotiable)

Only create or modify files inside `llm-wiki/` when performing wiki operations.

## Wiki command vocabulary

| User says | What to do |
|---|---|
| `wiki-ingest: <path>` | Run the ingest procedure from `llm-wiki/schema.md` |
| `wiki-query: <question>` | Run the query procedure from `llm-wiki/schema.md` |
| `wiki-super-summary: <id>` | Run the super summary procedure |
| `wiki-lint` | Run the lint procedure |

## Automated writes

Pages created or modified by the workflow orchestrator carry
`needs_review: true` in their frontmatter until a human clears the flag.
"""


def init_wiki_repo(repo_root: Path, *, seed_from: Path | None = None) -> list[str]:
    """Create the §4.5 layout. Returns the entries that were created."""
    layout = layout_for(repo_root)
    created: list[str] = []

    def ensure_dir(path: Path, label: str) -> None:
        if not path.is_dir():
            path.mkdir(parents=True, exist_ok=True)
            created.append(label)

    def ensure_file(path: Path, content: str, label: str) -> None:
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            created.append(label)

    ensure_dir(layout.repo_root, str(repo_root))
    ensure_dir(layout.wiki_dir, f"{WIKI_ROOT}/")
    for name in PAGE_DIRS:
        ensure_dir(layout.page_dir(name), f"{WIKI_ROOT}/{name}/")

    ensure_file(layout.index_md, INDEX_TEMPLATE, f"{WIKI_ROOT}/index.md")
    ensure_file(layout.log_md, LOG_TEMPLATE, f"{WIKI_ROOT}/log.md")

    seeded_schema = False
    seeded_agents = False
    if seed_from is not None:
        source = Path(seed_from).expanduser()
        # The source vault may nest pages one level deeper (llm-wiki/wiki/...),
        # so look for schema.md in both shapes.
        for candidate in (
            source / WIKI_ROOT / "schema.md",
            source / "schema.md",
        ):
            if candidate.exists() and not layout.schema_md.exists():
                shutil.copyfile(candidate, layout.schema_md)
                created.append(f"{WIKI_ROOT}/schema.md (seeded)")
                seeded_schema = True
                break
        agents_source = source / AGENTS_FILE
        if agents_source.exists() and not layout.agents_md.exists():
            shutil.copyfile(agents_source, layout.agents_md)
            created.append(f"{AGENTS_FILE} (seeded)")
            seeded_agents = True

    if not seeded_schema:
        ensure_file(layout.schema_md, SCHEMA_PLACEHOLDER, f"{WIKI_ROOT}/schema.md")
    if not seeded_agents:
        ensure_file(layout.agents_md, AGENTS_PLACEHOLDER, AGENTS_FILE)

    log.info(
        "wiki.initialized",
        repo_root=str(repo_root),
        created=len(created),
        seeded_from=str(seed_from) if seed_from else None,
    )
    return created
